#!/bin/sh


SECTION_HEADER="------------------------------"


echo $SECTION_HEADER
echo "concatenate and compile .less"
echo $SECTION_HEADER

cd static/style
./update

echo $SECTION_HEADER
echo "jinja process templates"
echo $SECTION_HEADER

cd ../../
python -m ybp_builder . static/_templates
